# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        <?php echo sfConfig::get('app_name_app'); ?>
    
  stylesheets:    
    - main.css
    - jq/jqueryslidemenu.css
    - validationEngineBackend.jquery.css
    - /js/extjs/resources/css/ext-all.css
    #- /js/fancybox/jquery.fancybox-1.3.4.css
    - cupertino/jquery-ui-1.8.1.custom.css


  javascripts:    
    - main
    - jq/jq.ajaxupload.js
    - jq/jqueryslidemenu.js
    - lynxCms.js
    - /js/extjs/adapter/ext/ext-base
    - /js/extjs/ext-all
    - jq/jquery-ui-1.8.1.custom.min.js
    - jq/jquery.ui.widget.js
    - jq/jquery.ui.mouse.js
    - jq/jquery.ui.sortable.js
    #- fancybox/jquery.fancybox-1.3.4.js
    - jq/jquery.validationEngine.js
    - jq/jquery.validationEngine-en_US.js
    - jq/jquery.price_format.1.8.js

  has_layout:     true
  layout:         layout
