<?php

/**
 * Base static class for performing query and update operations on the 'cadastro' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 03/04/2014 12:04:41
 *
 * @package    lib.model.sgws.om
 */
abstract class BaseCadastroPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'cadastro';

	/** the related Propel class for this table */
	const OM_CLASS = 'Cadastro';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.sgws.Cadastro';

	/** the related TableMap class for this table */
	const TM_CLASS = 'CadastroTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 44;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the CODIGOCADASTRO field */
	const CODIGOCADASTRO = 'cadastro.CODIGOCADASTRO';

	/** the column name for the TIPOCADASTRO field */
	const TIPOCADASTRO = 'cadastro.TIPOCADASTRO';

	/** the column name for the RAZAOSOCIAL field */
	const RAZAOSOCIAL = 'cadastro.RAZAOSOCIAL';

	/** the column name for the NOMEFANTASIA field */
	const NOMEFANTASIA = 'cadastro.NOMEFANTASIA';

	/** the column name for the CNPJ field */
	const CNPJ = 'cadastro.CNPJ';

	/** the column name for the INSCRICAOESTADUAL field */
	const INSCRICAOESTADUAL = 'cadastro.INSCRICAOESTADUAL';

	/** the column name for the INSCRICAOCOM field */
	const INSCRICAOCOM = 'cadastro.INSCRICAOCOM';

	/** the column name for the ENDERECO field */
	const ENDERECO = 'cadastro.ENDERECO';

	/** the column name for the NUMERO field */
	const NUMERO = 'cadastro.NUMERO';

	/** the column name for the COMPLEMENTO field */
	const COMPLEMENTO = 'cadastro.COMPLEMENTO';

	/** the column name for the BAIRRO field */
	const BAIRRO = 'cadastro.BAIRRO';

	/** the column name for the CIDADE field */
	const CIDADE = 'cadastro.CIDADE';

	/** the column name for the CEP field */
	const CEP = 'cadastro.CEP';

	/** the column name for the ESTADO field */
	const ESTADO = 'cadastro.ESTADO';

	/** the column name for the PAIS field */
	const PAIS = 'cadastro.PAIS';

	/** the column name for the TELEFONE field */
	const TELEFONE = 'cadastro.TELEFONE';

	/** the column name for the FAX field */
	const FAX = 'cadastro.FAX';

	/** the column name for the EMAIL field */
	const EMAIL = 'cadastro.EMAIL';

	/** the column name for the CONTATO1 field */
	const CONTATO1 = 'cadastro.CONTATO1';

	/** the column name for the TELEFONECON1 field */
	const TELEFONECON1 = 'cadastro.TELEFONECON1';

	/** the column name for the CELULARCON1 field */
	const CELULARCON1 = 'cadastro.CELULARCON1';

	/** the column name for the EMAILCONTATO1 field */
	const EMAILCONTATO1 = 'cadastro.EMAILCONTATO1';

	/** the column name for the CONTATO2 field */
	const CONTATO2 = 'cadastro.CONTATO2';

	/** the column name for the TELEFONECON2 field */
	const TELEFONECON2 = 'cadastro.TELEFONECON2';

	/** the column name for the CELULARCON2 field */
	const CELULARCON2 = 'cadastro.CELULARCON2';

	/** the column name for the EMAILCONTATO2 field */
	const EMAILCONTATO2 = 'cadastro.EMAILCONTATO2';

	/** the column name for the CONTATO3 field */
	const CONTATO3 = 'cadastro.CONTATO3';

	/** the column name for the TELEFONECON3 field */
	const TELEFONECON3 = 'cadastro.TELEFONECON3';

	/** the column name for the CELULARCON3 field */
	const CELULARCON3 = 'cadastro.CELULARCON3';

	/** the column name for the EMAILCONTATO3 field */
	const EMAILCONTATO3 = 'cadastro.EMAILCONTATO3';

	/** the column name for the CONTATO4 field */
	const CONTATO4 = 'cadastro.CONTATO4';

	/** the column name for the TELEFONECON4 field */
	const TELEFONECON4 = 'cadastro.TELEFONECON4';

	/** the column name for the CELULARCON4 field */
	const CELULARCON4 = 'cadastro.CELULARCON4';

	/** the column name for the EMAILCONTATO4 field */
	const EMAILCONTATO4 = 'cadastro.EMAILCONTATO4';

	/** the column name for the CONTATO5 field */
	const CONTATO5 = 'cadastro.CONTATO5';

	/** the column name for the TELEFONECON5 field */
	const TELEFONECON5 = 'cadastro.TELEFONECON5';

	/** the column name for the CELULARCON5 field */
	const CELULARCON5 = 'cadastro.CELULARCON5';

	/** the column name for the EMAILCONTATO5 field */
	const EMAILCONTATO5 = 'cadastro.EMAILCONTATO5';

	/** the column name for the ENDERECOSITE field */
	const ENDERECOSITE = 'cadastro.ENDERECOSITE';

	/** the column name for the NIVELPRIVACIDADE field */
	const NIVELPRIVACIDADE = 'cadastro.NIVELPRIVACIDADE';

	/** the column name for the CODIGOCLIENTE field */
	const CODIGOCLIENTE = 'cadastro.CODIGOCLIENTE';

	/** the column name for the SUBTIPO field */
	const SUBTIPO = 'cadastro.SUBTIPO';

	/** the column name for the CATEGORIA field */
	const CATEGORIA = 'cadastro.CATEGORIA';

	/** the column name for the STATUS field */
	const STATUS = 'cadastro.STATUS';

	/**
	 * An identiy map to hold any loaded instances of Cadastro objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Cadastro[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Codigocadastro', 'Tipocadastro', 'Razaosocial', 'Nomefantasia', 'Cnpj', 'Inscricaoestadual', 'Inscricaocom', 'Endereco', 'Numero', 'Complemento', 'Bairro', 'Cidade', 'Cep', 'Estado', 'Pais', 'Telefone', 'Fax', 'Email', 'Contato1', 'Telefonecon1', 'Celularcon1', 'Emailcontato1', 'Contato2', 'Telefonecon2', 'Celularcon2', 'Emailcontato2', 'Contato3', 'Telefonecon3', 'Celularcon3', 'Emailcontato3', 'Contato4', 'Telefonecon4', 'Celularcon4', 'Emailcontato4', 'Contato5', 'Telefonecon5', 'Celularcon5', 'Emailcontato5', 'Enderecosite', 'Nivelprivacidade', 'Codigocliente', 'Subtipo', 'Categoria', 'Status', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('codigocadastro', 'tipocadastro', 'razaosocial', 'nomefantasia', 'cnpj', 'inscricaoestadual', 'inscricaocom', 'endereco', 'numero', 'complemento', 'bairro', 'cidade', 'cep', 'estado', 'pais', 'telefone', 'fax', 'email', 'contato1', 'telefonecon1', 'celularcon1', 'emailcontato1', 'contato2', 'telefonecon2', 'celularcon2', 'emailcontato2', 'contato3', 'telefonecon3', 'celularcon3', 'emailcontato3', 'contato4', 'telefonecon4', 'celularcon4', 'emailcontato4', 'contato5', 'telefonecon5', 'celularcon5', 'emailcontato5', 'enderecosite', 'nivelprivacidade', 'codigocliente', 'subtipo', 'categoria', 'status', ),
		BasePeer::TYPE_COLNAME => array (self::CODIGOCADASTRO, self::TIPOCADASTRO, self::RAZAOSOCIAL, self::NOMEFANTASIA, self::CNPJ, self::INSCRICAOESTADUAL, self::INSCRICAOCOM, self::ENDERECO, self::NUMERO, self::COMPLEMENTO, self::BAIRRO, self::CIDADE, self::CEP, self::ESTADO, self::PAIS, self::TELEFONE, self::FAX, self::EMAIL, self::CONTATO1, self::TELEFONECON1, self::CELULARCON1, self::EMAILCONTATO1, self::CONTATO2, self::TELEFONECON2, self::CELULARCON2, self::EMAILCONTATO2, self::CONTATO3, self::TELEFONECON3, self::CELULARCON3, self::EMAILCONTATO3, self::CONTATO4, self::TELEFONECON4, self::CELULARCON4, self::EMAILCONTATO4, self::CONTATO5, self::TELEFONECON5, self::CELULARCON5, self::EMAILCONTATO5, self::ENDERECOSITE, self::NIVELPRIVACIDADE, self::CODIGOCLIENTE, self::SUBTIPO, self::CATEGORIA, self::STATUS, ),
		BasePeer::TYPE_FIELDNAME => array ('codigocadastro', 'TipoCadastro', 'RazaoSocial', 'NomeFantasia', 'CNPJ', 'InscricaoEstadual', 'InscricaoCom', 'Endereco', 'Numero', 'Complemento', 'Bairro', 'Cidade', 'CEP', 'Estado', 'Pais', 'Telefone', 'Fax', 'email', 'Contato1', 'TelefoneCon1', 'CelularCon1', 'EmailContato1', 'Contato2', 'TelefoneCon2', 'CelularCon2', 'EmailContato2', 'Contato3', 'TelefoneCon3', 'CelularCon3', 'EmailContato3', 'Contato4', 'TelefoneCon4', 'CelularCon4', 'EmailContato4', 'Contato5', 'TelefoneCon5', 'CelularCon5', 'EmailContato5', 'EnderecoSite', 'nivelprivacidade', 'codigocliente', 'subtipo', 'categoria', 'status', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Codigocadastro' => 0, 'Tipocadastro' => 1, 'Razaosocial' => 2, 'Nomefantasia' => 3, 'Cnpj' => 4, 'Inscricaoestadual' => 5, 'Inscricaocom' => 6, 'Endereco' => 7, 'Numero' => 8, 'Complemento' => 9, 'Bairro' => 10, 'Cidade' => 11, 'Cep' => 12, 'Estado' => 13, 'Pais' => 14, 'Telefone' => 15, 'Fax' => 16, 'Email' => 17, 'Contato1' => 18, 'Telefonecon1' => 19, 'Celularcon1' => 20, 'Emailcontato1' => 21, 'Contato2' => 22, 'Telefonecon2' => 23, 'Celularcon2' => 24, 'Emailcontato2' => 25, 'Contato3' => 26, 'Telefonecon3' => 27, 'Celularcon3' => 28, 'Emailcontato3' => 29, 'Contato4' => 30, 'Telefonecon4' => 31, 'Celularcon4' => 32, 'Emailcontato4' => 33, 'Contato5' => 34, 'Telefonecon5' => 35, 'Celularcon5' => 36, 'Emailcontato5' => 37, 'Enderecosite' => 38, 'Nivelprivacidade' => 39, 'Codigocliente' => 40, 'Subtipo' => 41, 'Categoria' => 42, 'Status' => 43, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('codigocadastro' => 0, 'tipocadastro' => 1, 'razaosocial' => 2, 'nomefantasia' => 3, 'cnpj' => 4, 'inscricaoestadual' => 5, 'inscricaocom' => 6, 'endereco' => 7, 'numero' => 8, 'complemento' => 9, 'bairro' => 10, 'cidade' => 11, 'cep' => 12, 'estado' => 13, 'pais' => 14, 'telefone' => 15, 'fax' => 16, 'email' => 17, 'contato1' => 18, 'telefonecon1' => 19, 'celularcon1' => 20, 'emailcontato1' => 21, 'contato2' => 22, 'telefonecon2' => 23, 'celularcon2' => 24, 'emailcontato2' => 25, 'contato3' => 26, 'telefonecon3' => 27, 'celularcon3' => 28, 'emailcontato3' => 29, 'contato4' => 30, 'telefonecon4' => 31, 'celularcon4' => 32, 'emailcontato4' => 33, 'contato5' => 34, 'telefonecon5' => 35, 'celularcon5' => 36, 'emailcontato5' => 37, 'enderecosite' => 38, 'nivelprivacidade' => 39, 'codigocliente' => 40, 'subtipo' => 41, 'categoria' => 42, 'status' => 43, ),
		BasePeer::TYPE_COLNAME => array (self::CODIGOCADASTRO => 0, self::TIPOCADASTRO => 1, self::RAZAOSOCIAL => 2, self::NOMEFANTASIA => 3, self::CNPJ => 4, self::INSCRICAOESTADUAL => 5, self::INSCRICAOCOM => 6, self::ENDERECO => 7, self::NUMERO => 8, self::COMPLEMENTO => 9, self::BAIRRO => 10, self::CIDADE => 11, self::CEP => 12, self::ESTADO => 13, self::PAIS => 14, self::TELEFONE => 15, self::FAX => 16, self::EMAIL => 17, self::CONTATO1 => 18, self::TELEFONECON1 => 19, self::CELULARCON1 => 20, self::EMAILCONTATO1 => 21, self::CONTATO2 => 22, self::TELEFONECON2 => 23, self::CELULARCON2 => 24, self::EMAILCONTATO2 => 25, self::CONTATO3 => 26, self::TELEFONECON3 => 27, self::CELULARCON3 => 28, self::EMAILCONTATO3 => 29, self::CONTATO4 => 30, self::TELEFONECON4 => 31, self::CELULARCON4 => 32, self::EMAILCONTATO4 => 33, self::CONTATO5 => 34, self::TELEFONECON5 => 35, self::CELULARCON5 => 36, self::EMAILCONTATO5 => 37, self::ENDERECOSITE => 38, self::NIVELPRIVACIDADE => 39, self::CODIGOCLIENTE => 40, self::SUBTIPO => 41, self::CATEGORIA => 42, self::STATUS => 43, ),
		BasePeer::TYPE_FIELDNAME => array ('codigocadastro' => 0, 'TipoCadastro' => 1, 'RazaoSocial' => 2, 'NomeFantasia' => 3, 'CNPJ' => 4, 'InscricaoEstadual' => 5, 'InscricaoCom' => 6, 'Endereco' => 7, 'Numero' => 8, 'Complemento' => 9, 'Bairro' => 10, 'Cidade' => 11, 'CEP' => 12, 'Estado' => 13, 'Pais' => 14, 'Telefone' => 15, 'Fax' => 16, 'email' => 17, 'Contato1' => 18, 'TelefoneCon1' => 19, 'CelularCon1' => 20, 'EmailContato1' => 21, 'Contato2' => 22, 'TelefoneCon2' => 23, 'CelularCon2' => 24, 'EmailContato2' => 25, 'Contato3' => 26, 'TelefoneCon3' => 27, 'CelularCon3' => 28, 'EmailContato3' => 29, 'Contato4' => 30, 'TelefoneCon4' => 31, 'CelularCon4' => 32, 'EmailContato4' => 33, 'Contato5' => 34, 'TelefoneCon5' => 35, 'CelularCon5' => 36, 'EmailContato5' => 37, 'EnderecoSite' => 38, 'nivelprivacidade' => 39, 'codigocliente' => 40, 'subtipo' => 41, 'categoria' => 42, 'status' => 43, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. CadastroPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(CadastroPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(CadastroPeer::CODIGOCADASTRO);
		$criteria->addSelectColumn(CadastroPeer::TIPOCADASTRO);
		$criteria->addSelectColumn(CadastroPeer::RAZAOSOCIAL);
		$criteria->addSelectColumn(CadastroPeer::NOMEFANTASIA);
		$criteria->addSelectColumn(CadastroPeer::CNPJ);
		$criteria->addSelectColumn(CadastroPeer::INSCRICAOESTADUAL);
		$criteria->addSelectColumn(CadastroPeer::INSCRICAOCOM);
		$criteria->addSelectColumn(CadastroPeer::ENDERECO);
		$criteria->addSelectColumn(CadastroPeer::NUMERO);
		$criteria->addSelectColumn(CadastroPeer::COMPLEMENTO);
		$criteria->addSelectColumn(CadastroPeer::BAIRRO);
		$criteria->addSelectColumn(CadastroPeer::CIDADE);
		$criteria->addSelectColumn(CadastroPeer::CEP);
		$criteria->addSelectColumn(CadastroPeer::ESTADO);
		$criteria->addSelectColumn(CadastroPeer::PAIS);
		$criteria->addSelectColumn(CadastroPeer::TELEFONE);
		$criteria->addSelectColumn(CadastroPeer::FAX);
		$criteria->addSelectColumn(CadastroPeer::EMAIL);
		$criteria->addSelectColumn(CadastroPeer::CONTATO1);
		$criteria->addSelectColumn(CadastroPeer::TELEFONECON1);
		$criteria->addSelectColumn(CadastroPeer::CELULARCON1);
		$criteria->addSelectColumn(CadastroPeer::EMAILCONTATO1);
		$criteria->addSelectColumn(CadastroPeer::CONTATO2);
		$criteria->addSelectColumn(CadastroPeer::TELEFONECON2);
		$criteria->addSelectColumn(CadastroPeer::CELULARCON2);
		$criteria->addSelectColumn(CadastroPeer::EMAILCONTATO2);
		$criteria->addSelectColumn(CadastroPeer::CONTATO3);
		$criteria->addSelectColumn(CadastroPeer::TELEFONECON3);
		$criteria->addSelectColumn(CadastroPeer::CELULARCON3);
		$criteria->addSelectColumn(CadastroPeer::EMAILCONTATO3);
		$criteria->addSelectColumn(CadastroPeer::CONTATO4);
		$criteria->addSelectColumn(CadastroPeer::TELEFONECON4);
		$criteria->addSelectColumn(CadastroPeer::CELULARCON4);
		$criteria->addSelectColumn(CadastroPeer::EMAILCONTATO4);
		$criteria->addSelectColumn(CadastroPeer::CONTATO5);
		$criteria->addSelectColumn(CadastroPeer::TELEFONECON5);
		$criteria->addSelectColumn(CadastroPeer::CELULARCON5);
		$criteria->addSelectColumn(CadastroPeer::EMAILCONTATO5);
		$criteria->addSelectColumn(CadastroPeer::ENDERECOSITE);
		$criteria->addSelectColumn(CadastroPeer::NIVELPRIVACIDADE);
		$criteria->addSelectColumn(CadastroPeer::CODIGOCLIENTE);
		$criteria->addSelectColumn(CadastroPeer::SUBTIPO);
		$criteria->addSelectColumn(CadastroPeer::CATEGORIA);
		$criteria->addSelectColumn(CadastroPeer::STATUS);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CadastroPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CadastroPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseCadastroPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Cadastro
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = CadastroPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return CadastroPeer::populateObjects(CadastroPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			CadastroPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Cadastro $value A Cadastro object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Cadastro $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getCodigocadastro();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Cadastro object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Cadastro) {
				$key = (string) $value->getCodigocadastro();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Cadastro object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Cadastro Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to cadastro
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = CadastroPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = CadastroPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = CadastroPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				CadastroPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseCadastroPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseCadastroPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new CadastroTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? CadastroPeer::CLASS_DEFAULT : CadastroPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Cadastro or Criteria object.
	 *
	 * @param      mixed $values Criteria or Cadastro object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseCadastroPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Cadastro object
		}

		if ($criteria->containsKey(CadastroPeer::CODIGOCADASTRO) && $criteria->keyContainsValue(CadastroPeer::CODIGOCADASTRO) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.CadastroPeer::CODIGOCADASTRO.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseCadastroPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Cadastro or Criteria object.
	 *
	 * @param      mixed $values Criteria or Cadastro object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseCadastroPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(CadastroPeer::CODIGOCADASTRO);
			$selectCriteria->add(CadastroPeer::CODIGOCADASTRO, $criteria->remove(CadastroPeer::CODIGOCADASTRO), $comparison);

		} else { // $values is Cadastro object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseCadastroPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the cadastro table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(CadastroPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			CadastroPeer::clearInstancePool();
			CadastroPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Cadastro or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Cadastro object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			CadastroPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Cadastro) { // it's a model object
			// invalidate the cache for this single object
			CadastroPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(CadastroPeer::CODIGOCADASTRO, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				CadastroPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			CadastroPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Cadastro object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Cadastro $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Cadastro $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(CadastroPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(CadastroPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(CadastroPeer::DATABASE_NAME, CadastroPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Cadastro
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = CadastroPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(CadastroPeer::DATABASE_NAME);
		$criteria->add(CadastroPeer::CODIGOCADASTRO, $pk);

		$v = CadastroPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(CadastroPeer::DATABASE_NAME);
			$criteria->add(CadastroPeer::CODIGOCADASTRO, $pks, Criteria::IN);
			$objs = CadastroPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseCadastroPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseCadastroPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseCadastroPeer::buildTableMap();

