<?php

/**
 * Base class that represents a row from the 'tarefa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 03/04/2014 12:04:44
 *
 * @package    lib.model.sgws.om
 */
abstract class BaseTarefa extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TarefaPeer
	 */
	protected static $peer;

	/**
	 * The value for the codigotarefa field.
	 * @var        int
	 */
	protected $codigotarefa;

	/**
	 * The value for the tarefa_parent field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $tarefa_parent;

	/**
	 * The value for the responsavel field.
	 * @var        int
	 */
	protected $responsavel;

	/**
	 * The value for the codigoprojeto field.
	 * @var        int
	 */
	protected $codigoprojeto;

	/**
	 * The value for the visualizacao field.
	 * @var        string
	 */
	protected $visualizacao;

	/**
	 * The value for the descricao field.
	 * @var        int
	 */
	protected $descricao;

	/**
	 * The value for the tipo_tarefa field.
	 * @var        int
	 */
	protected $tipo_tarefa;

	/**
	 * The value for the datairtarefa field.
	 * @var        string
	 */
	protected $datairtarefa;

	/**
	 * The value for the datafrtarefa field.
	 * @var        string
	 */
	protected $datafrtarefa;

	/**
	 * The value for the status field.
	 * @var        int
	 */
	protected $status;

	/**
	 * The value for the despesaprevista field.
	 * @var        string
	 */
	protected $despesaprevista;

	/**
	 * The value for the horasprevistas field.
	 * @var        string
	 */
	protected $horasprevistas;

	/**
	 * The value for the observacoes field.
	 * @var        string
	 */
	protected $observacoes;

	/**
	 * The value for the informacoes field.
	 * @var        string
	 */
	protected $informacoes;

	/**
	 * The value for the id_prioridade field.
	 * @var        int
	 */
	protected $id_prioridade;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TarefaPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->tarefa_parent = 0;
	}

	/**
	 * Initializes internal state of BaseTarefa object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [codigotarefa] column value.
	 * 
	 * @return     int
	 */
	public function getCodigotarefa()
	{
		return $this->codigotarefa;
	}

	/**
	 * Get the [tarefa_parent] column value.
	 * 
	 * @return     int
	 */
	public function getTarefaParent()
	{
		return $this->tarefa_parent;
	}

	/**
	 * Get the [responsavel] column value.
	 * 
	 * @return     int
	 */
	public function getResponsavel()
	{
		return $this->responsavel;
	}

	/**
	 * Get the [codigoprojeto] column value.
	 * 
	 * @return     int
	 */
	public function getCodigoprojeto()
	{
		return $this->codigoprojeto;
	}

	/**
	 * Get the [visualizacao] column value.
	 * 
	 * @return     string
	 */
	public function getVisualizacao()
	{
		return $this->visualizacao;
	}

	/**
	 * Get the [descricao] column value.
	 * 
	 * @return     int
	 */
	public function getDescricao()
	{
		return $this->descricao;
	}

	/**
	 * Get the [tipo_tarefa] column value.
	 * 
	 * @return     int
	 */
	public function getTipoTarefa()
	{
		return $this->tipo_tarefa;
	}

	/**
	 * Get the [optionally formatted] temporal [datairtarefa] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDatairtarefa($format = 'Y-m-d')
	{
		if ($this->datairtarefa === null) {
			return null;
		}


		if ($this->datairtarefa === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->datairtarefa);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->datairtarefa, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [datafrtarefa] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDatafrtarefa($format = 'Y-m-d')
	{
		if ($this->datafrtarefa === null) {
			return null;
		}


		if ($this->datafrtarefa === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->datafrtarefa);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->datafrtarefa, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     int
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [despesaprevista] column value.
	 * 
	 * @return     string
	 */
	public function getDespesaprevista()
	{
		return $this->despesaprevista;
	}

	/**
	 * Get the [horasprevistas] column value.
	 * 
	 * @return     string
	 */
	public function getHorasprevistas()
	{
		return $this->horasprevistas;
	}

	/**
	 * Get the [observacoes] column value.
	 * 
	 * @return     string
	 */
	public function getObservacoes()
	{
		return $this->observacoes;
	}

	/**
	 * Get the [informacoes] column value.
	 * 
	 * @return     string
	 */
	public function getInformacoes()
	{
		return $this->informacoes;
	}

	/**
	 * Get the [id_prioridade] column value.
	 * 
	 * @return     int
	 */
	public function getIdPrioridade()
	{
		return $this->id_prioridade;
	}

	/**
	 * Set the value of [codigotarefa] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setCodigotarefa($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->codigotarefa !== $v) {
			$this->codigotarefa = $v;
			$this->modifiedColumns[] = TarefaPeer::CODIGOTAREFA;
		}

		return $this;
	} // setCodigotarefa()

	/**
	 * Set the value of [tarefa_parent] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setTarefaParent($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tarefa_parent !== $v || $this->isNew()) {
			$this->tarefa_parent = $v;
			$this->modifiedColumns[] = TarefaPeer::TAREFA_PARENT;
		}

		return $this;
	} // setTarefaParent()

	/**
	 * Set the value of [responsavel] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setResponsavel($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->responsavel !== $v) {
			$this->responsavel = $v;
			$this->modifiedColumns[] = TarefaPeer::RESPONSAVEL;
		}

		return $this;
	} // setResponsavel()

	/**
	 * Set the value of [codigoprojeto] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setCodigoprojeto($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->codigoprojeto !== $v) {
			$this->codigoprojeto = $v;
			$this->modifiedColumns[] = TarefaPeer::CODIGOPROJETO;
		}

		return $this;
	} // setCodigoprojeto()

	/**
	 * Set the value of [visualizacao] column.
	 * 
	 * @param      string $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setVisualizacao($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->visualizacao !== $v) {
			$this->visualizacao = $v;
			$this->modifiedColumns[] = TarefaPeer::VISUALIZACAO;
		}

		return $this;
	} // setVisualizacao()

	/**
	 * Set the value of [descricao] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setDescricao($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->descricao !== $v) {
			$this->descricao = $v;
			$this->modifiedColumns[] = TarefaPeer::DESCRICAO;
		}

		return $this;
	} // setDescricao()

	/**
	 * Set the value of [tipo_tarefa] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setTipoTarefa($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tipo_tarefa !== $v) {
			$this->tipo_tarefa = $v;
			$this->modifiedColumns[] = TarefaPeer::TIPO_TAREFA;
		}

		return $this;
	} // setTipoTarefa()

	/**
	 * Sets the value of [datairtarefa] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setDatairtarefa($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->datairtarefa !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->datairtarefa !== null && $tmpDt = new DateTime($this->datairtarefa)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->datairtarefa = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = TarefaPeer::DATAIRTAREFA;
			}
		} // if either are not null

		return $this;
	} // setDatairtarefa()

	/**
	 * Sets the value of [datafrtarefa] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setDatafrtarefa($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->datafrtarefa !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->datafrtarefa !== null && $tmpDt = new DateTime($this->datafrtarefa)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->datafrtarefa = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = TarefaPeer::DATAFRTAREFA;
			}
		} // if either are not null

		return $this;
	} // setDatafrtarefa()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = TarefaPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [despesaprevista] column.
	 * 
	 * @param      string $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setDespesaprevista($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->despesaprevista !== $v) {
			$this->despesaprevista = $v;
			$this->modifiedColumns[] = TarefaPeer::DESPESAPREVISTA;
		}

		return $this;
	} // setDespesaprevista()

	/**
	 * Set the value of [horasprevistas] column.
	 * 
	 * @param      string $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setHorasprevistas($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->horasprevistas !== $v) {
			$this->horasprevistas = $v;
			$this->modifiedColumns[] = TarefaPeer::HORASPREVISTAS;
		}

		return $this;
	} // setHorasprevistas()

	/**
	 * Set the value of [observacoes] column.
	 * 
	 * @param      string $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setObservacoes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->observacoes !== $v) {
			$this->observacoes = $v;
			$this->modifiedColumns[] = TarefaPeer::OBSERVACOES;
		}

		return $this;
	} // setObservacoes()

	/**
	 * Set the value of [informacoes] column.
	 * 
	 * @param      string $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setInformacoes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->informacoes !== $v) {
			$this->informacoes = $v;
			$this->modifiedColumns[] = TarefaPeer::INFORMACOES;
		}

		return $this;
	} // setInformacoes()

	/**
	 * Set the value of [id_prioridade] column.
	 * 
	 * @param      int $v new value
	 * @return     Tarefa The current object (for fluent API support)
	 */
	public function setIdPrioridade($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_prioridade !== $v) {
			$this->id_prioridade = $v;
			$this->modifiedColumns[] = TarefaPeer::ID_PRIORIDADE;
		}

		return $this;
	} // setIdPrioridade()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->tarefa_parent !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->codigotarefa = (isset($row[$startcol + 0]) && $row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->tarefa_parent = (isset($row[$startcol + 1]) && $row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->responsavel = (isset($row[$startcol + 2]) && $row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->codigoprojeto = (isset($row[$startcol + 3]) && $row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->visualizacao = (isset($row[$startcol + 4]) && $row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->descricao = (isset($row[$startcol + 5]) && $row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->tipo_tarefa = (isset($row[$startcol + 6]) && $row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->datairtarefa = (isset($row[$startcol + 7]) && $row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->datafrtarefa = (isset($row[$startcol + 8]) && $row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->status = (isset($row[$startcol + 9]) && $row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->despesaprevista = (isset($row[$startcol + 10]) && $row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->horasprevistas = (isset($row[$startcol + 11]) && $row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->observacoes = (isset($row[$startcol + 12]) && $row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->informacoes = (isset($row[$startcol + 13]) && $row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->id_prioridade = (isset($row[$startcol + 14]) && $row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = TarefaPeer::NUM_COLUMNS - TarefaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tarefa object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TarefaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TarefaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TarefaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTarefa:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				TarefaPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTarefa:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TarefaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTarefa:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTarefa:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				TarefaPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TarefaPeer::CODIGOTAREFA;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TarefaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCodigotarefa($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TarefaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = TarefaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TarefaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCodigotarefa();
				break;
			case 1:
				return $this->getTarefaParent();
				break;
			case 2:
				return $this->getResponsavel();
				break;
			case 3:
				return $this->getCodigoprojeto();
				break;
			case 4:
				return $this->getVisualizacao();
				break;
			case 5:
				return $this->getDescricao();
				break;
			case 6:
				return $this->getTipoTarefa();
				break;
			case 7:
				return $this->getDatairtarefa();
				break;
			case 8:
				return $this->getDatafrtarefa();
				break;
			case 9:
				return $this->getStatus();
				break;
			case 10:
				return $this->getDespesaprevista();
				break;
			case 11:
				return $this->getHorasprevistas();
				break;
			case 12:
				return $this->getObservacoes();
				break;
			case 13:
				return $this->getInformacoes();
				break;
			case 14:
				return $this->getIdPrioridade();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TarefaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCodigotarefa(),
			$keys[1] => $this->getTarefaParent(),
			$keys[2] => $this->getResponsavel(),
			$keys[3] => $this->getCodigoprojeto(),
			$keys[4] => $this->getVisualizacao(),
			$keys[5] => $this->getDescricao(),
			$keys[6] => $this->getTipoTarefa(),
			$keys[7] => $this->getDatairtarefa(),
			$keys[8] => $this->getDatafrtarefa(),
			$keys[9] => $this->getStatus(),
			$keys[10] => $this->getDespesaprevista(),
			$keys[11] => $this->getHorasprevistas(),
			$keys[12] => $this->getObservacoes(),
			$keys[13] => $this->getInformacoes(),
			$keys[14] => $this->getIdPrioridade(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TarefaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCodigotarefa($value);
				break;
			case 1:
				$this->setTarefaParent($value);
				break;
			case 2:
				$this->setResponsavel($value);
				break;
			case 3:
				$this->setCodigoprojeto($value);
				break;
			case 4:
				$this->setVisualizacao($value);
				break;
			case 5:
				$this->setDescricao($value);
				break;
			case 6:
				$this->setTipoTarefa($value);
				break;
			case 7:
				$this->setDatairtarefa($value);
				break;
			case 8:
				$this->setDatafrtarefa($value);
				break;
			case 9:
				$this->setStatus($value);
				break;
			case 10:
				$this->setDespesaprevista($value);
				break;
			case 11:
				$this->setHorasprevistas($value);
				break;
			case 12:
				$this->setObservacoes($value);
				break;
			case 13:
				$this->setInformacoes($value);
				break;
			case 14:
				$this->setIdPrioridade($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TarefaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCodigotarefa($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTarefaParent($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setResponsavel($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCodigoprojeto($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setVisualizacao($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDescricao($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setTipoTarefa($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDatairtarefa($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDatafrtarefa($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setStatus($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDespesaprevista($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setHorasprevistas($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setObservacoes($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setInformacoes($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setIdPrioridade($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TarefaPeer::DATABASE_NAME);

		if ($this->isColumnModified(TarefaPeer::CODIGOTAREFA)) $criteria->add(TarefaPeer::CODIGOTAREFA, $this->codigotarefa);
		if ($this->isColumnModified(TarefaPeer::TAREFA_PARENT)) $criteria->add(TarefaPeer::TAREFA_PARENT, $this->tarefa_parent);
		if ($this->isColumnModified(TarefaPeer::RESPONSAVEL)) $criteria->add(TarefaPeer::RESPONSAVEL, $this->responsavel);
		if ($this->isColumnModified(TarefaPeer::CODIGOPROJETO)) $criteria->add(TarefaPeer::CODIGOPROJETO, $this->codigoprojeto);
		if ($this->isColumnModified(TarefaPeer::VISUALIZACAO)) $criteria->add(TarefaPeer::VISUALIZACAO, $this->visualizacao);
		if ($this->isColumnModified(TarefaPeer::DESCRICAO)) $criteria->add(TarefaPeer::DESCRICAO, $this->descricao);
		if ($this->isColumnModified(TarefaPeer::TIPO_TAREFA)) $criteria->add(TarefaPeer::TIPO_TAREFA, $this->tipo_tarefa);
		if ($this->isColumnModified(TarefaPeer::DATAIRTAREFA)) $criteria->add(TarefaPeer::DATAIRTAREFA, $this->datairtarefa);
		if ($this->isColumnModified(TarefaPeer::DATAFRTAREFA)) $criteria->add(TarefaPeer::DATAFRTAREFA, $this->datafrtarefa);
		if ($this->isColumnModified(TarefaPeer::STATUS)) $criteria->add(TarefaPeer::STATUS, $this->status);
		if ($this->isColumnModified(TarefaPeer::DESPESAPREVISTA)) $criteria->add(TarefaPeer::DESPESAPREVISTA, $this->despesaprevista);
		if ($this->isColumnModified(TarefaPeer::HORASPREVISTAS)) $criteria->add(TarefaPeer::HORASPREVISTAS, $this->horasprevistas);
		if ($this->isColumnModified(TarefaPeer::OBSERVACOES)) $criteria->add(TarefaPeer::OBSERVACOES, $this->observacoes);
		if ($this->isColumnModified(TarefaPeer::INFORMACOES)) $criteria->add(TarefaPeer::INFORMACOES, $this->informacoes);
		if ($this->isColumnModified(TarefaPeer::ID_PRIORIDADE)) $criteria->add(TarefaPeer::ID_PRIORIDADE, $this->id_prioridade);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TarefaPeer::DATABASE_NAME);

		$criteria->add(TarefaPeer::CODIGOTAREFA, $this->codigotarefa);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getCodigotarefa();
	}

	/**
	 * Generic method to set the primary key (codigotarefa column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCodigotarefa($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tarefa (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTarefaParent($this->tarefa_parent);

		$copyObj->setResponsavel($this->responsavel);

		$copyObj->setCodigoprojeto($this->codigoprojeto);

		$copyObj->setVisualizacao($this->visualizacao);

		$copyObj->setDescricao($this->descricao);

		$copyObj->setTipoTarefa($this->tipo_tarefa);

		$copyObj->setDatairtarefa($this->datairtarefa);

		$copyObj->setDatafrtarefa($this->datafrtarefa);

		$copyObj->setStatus($this->status);

		$copyObj->setDespesaprevista($this->despesaprevista);

		$copyObj->setHorasprevistas($this->horasprevistas);

		$copyObj->setObservacoes($this->observacoes);

		$copyObj->setInformacoes($this->informacoes);

		$copyObj->setIdPrioridade($this->id_prioridade);


		$copyObj->setNew(true);

		$copyObj->setCodigotarefa(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tarefa Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TarefaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TarefaPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTarefa:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTarefa::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTarefa
