<?php

/**
 * Base static class for performing query and update operations on the 'analisis' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 03/04/2014 12:04:41
 *
 * @package    lib.model.sgws.om
 */
abstract class BaseAnalisisPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'analisis';

	/** the related Propel class for this table */
	const OM_CLASS = 'Analisis';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.sgws.Analisis';

	/** the related TableMap class for this table */
	const TM_CLASS = 'AnalisisTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 37;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'analisis.ID';

	/** the column name for the ANALISIS_PPAL field */
	const ANALISIS_PPAL = 'analisis.ANALISIS_PPAL';

	/** the column name for the ID_PROPOSTA_ANEXO field */
	const ID_PROPOSTA_ANEXO = 'analisis.ID_PROPOSTA_ANEXO';

	/** the column name for the ID_PROPOSTA field */
	const ID_PROPOSTA = 'analisis.ID_PROPOSTA';

	/** the column name for the ID_RESPONSAVEL field */
	const ID_RESPONSAVEL = 'analisis.ID_RESPONSAVEL';

	/** the column name for the ID_CLIENTE field */
	const ID_CLIENTE = 'analisis.ID_CLIENTE';

	/** the column name for the STATUS field */
	const STATUS = 'analisis.STATUS';

	/** the column name for the DATA_CREACION field */
	const DATA_CREACION = 'analisis.DATA_CREACION';

	/** the column name for the DATA_APROBACION field */
	const DATA_APROBACION = 'analisis.DATA_APROBACION';

	/** the column name for the DESCRICAO field */
	const DESCRICAO = 'analisis.DESCRICAO';

	/** the column name for the PLAZO field */
	const PLAZO = 'analisis.PLAZO';

	/** the column name for the VIABILIDADE_TECNICA field */
	const VIABILIDADE_TECNICA = 'analisis.VIABILIDADE_TECNICA';

	/** the column name for the EQUIPAMENTO_APROPIADO field */
	const EQUIPAMENTO_APROPIADO = 'analisis.EQUIPAMENTO_APROPIADO';

	/** the column name for the METODOLOGIA_VALIDADA field */
	const METODOLOGIA_VALIDADA = 'analisis.METODOLOGIA_VALIDADA';

	/** the column name for the QUANTIDADE_AMOSTRA field */
	const QUANTIDADE_AMOSTRA = 'analisis.QUANTIDADE_AMOSTRA';

	/** the column name for the VIABILIDADE_OPERACIONAL field */
	const VIABILIDADE_OPERACIONAL = 'analisis.VIABILIDADE_OPERACIONAL';

	/** the column name for the TECNICO_HABILITADO field */
	const TECNICO_HABILITADO = 'analisis.TECNICO_HABILITADO';

	/** the column name for the MANO_OBRA field */
	const MANO_OBRA = 'analisis.MANO_OBRA';

	/** the column name for the PLAZO_EXEQUIVEL field */
	const PLAZO_EXEQUIVEL = 'analisis.PLAZO_EXEQUIVEL';

	/** the column name for the VIABILIDADE_FINANCIERA field */
	const VIABILIDADE_FINANCIERA = 'analisis.VIABILIDADE_FINANCIERA';

	/** the column name for the VALOR_ADECUADO field */
	const VALOR_ADECUADO = 'analisis.VALOR_ADECUADO';

	/** the column name for the PLAZO_PAGAMENTO field */
	const PLAZO_PAGAMENTO = 'analisis.PLAZO_PAGAMENTO';

	/** the column name for the TERCERIZADO field */
	const TERCERIZADO = 'analisis.TERCERIZADO';

	/** the column name for the ID_FORNECEDOR field */
	const ID_FORNECEDOR = 'analisis.ID_FORNECEDOR';

	/** the column name for the VALOR_PROPOSTA field */
	const VALOR_PROPOSTA = 'analisis.VALOR_PROPOSTA';

	/** the column name for the APROBACION_CLIENTE field */
	const APROBACION_CLIENTE = 'analisis.APROBACION_CLIENTE';

	/** the column name for the RESPONSABLE_COMERCIAL field */
	const RESPONSABLE_COMERCIAL = 'analisis.RESPONSABLE_COMERCIAL';

	/** the column name for the APROBADO_RESPONSABLE_COMERCIAL field */
	const APROBADO_RESPONSABLE_COMERCIAL = 'analisis.APROBADO_RESPONSABLE_COMERCIAL';

	/** the column name for the RESPONSABLE_TECNICO field */
	const RESPONSABLE_TECNICO = 'analisis.RESPONSABLE_TECNICO';

	/** the column name for the APROBADO_RESPONSABLE_TECNICO field */
	const APROBADO_RESPONSABLE_TECNICO = 'analisis.APROBADO_RESPONSABLE_TECNICO';

	/** the column name for the APROBACION_PROPOSTA field */
	const APROBACION_PROPOSTA = 'analisis.APROBACION_PROPOSTA';

	/** the column name for the CODIGO_PROPOSTA_FINAL field */
	const CODIGO_PROPOSTA_FINAL = 'analisis.CODIGO_PROPOSTA_FINAL';

	/** the column name for the VALIDADE_PROPOSTA field */
	const VALIDADE_PROPOSTA = 'analisis.VALIDADE_PROPOSTA';

	/** the column name for the FORMA_APROBACION field */
	const FORMA_APROBACION = 'analisis.FORMA_APROBACION';

	/** the column name for the PRECIO field */
	const PRECIO = 'analisis.PRECIO';
        
        /** the column name for the NOME field */
	const NOME = 'analisis.NOME';

	/** the column name for the FORMA_PAGAMENTO field */
	const FORMA_PAGAMENTO = 'analisis.FORMA_PAGAMENTO';

	/**
	 * An identiy map to hold any loaded instances of Analisis objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Analisis[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'AnalisisPpal', 'IdPropostaAnexo', 'IdProposta', 'IdResponsavel', 'IdCliente', 'Status', 'DataCreacion', 'DataAprobacion', 'Descricao', 'Plazo', 'ViabilidadeTecnica', 'EquipamentoApropiado', 'MetodologiaValidada', 'QuantidadeAmostra', 'ViabilidadeOperacional', 'TecnicoHabilitado', 'ManoObra', 'PlazoExequivel', 'ViabilidadeFinanciera', 'ValorAdecuado', 'PlazoPagamento', 'Tercerizado', 'IdFornecedor', 'ValorProposta', 'AprobacionCliente', 'ResponsableComercial', 'AprobadoResponsableComercial', 'ResponsableTecnico', 'AprobadoResponsableTecnico', 'AprobacionProposta', 'CodigoPropostaFinal', 'ValidadeProposta', 'FormaAprobacion', 'Precio', 'FormaPagamento','Nome' ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'analisisPpal', 'idPropostaAnexo', 'idProposta', 'idResponsavel', 'idCliente', 'status', 'dataCreacion', 'dataAprobacion', 'descricao', 'plazo', 'viabilidadeTecnica', 'equipamentoApropiado', 'metodologiaValidada', 'quantidadeAmostra', 'viabilidadeOperacional', 'tecnicoHabilitado', 'manoObra', 'plazoExequivel', 'viabilidadeFinanciera', 'valorAdecuado', 'plazoPagamento', 'tercerizado', 'idFornecedor', 'valorProposta', 'aprobacionCliente', 'responsableComercial', 'aprobadoResponsableComercial', 'responsableTecnico', 'aprobadoResponsableTecnico', 'aprobacionProposta', 'codigoPropostaFinal', 'validadeProposta', 'formaAprobacion', 'precio', 'formaPagamento','nome' ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::ANALISIS_PPAL, self::ID_PROPOSTA_ANEXO, self::ID_PROPOSTA, self::ID_RESPONSAVEL, self::ID_CLIENTE, self::STATUS, self::DATA_CREACION, self::DATA_APROBACION, self::DESCRICAO, self::PLAZO, self::VIABILIDADE_TECNICA, self::EQUIPAMENTO_APROPIADO, self::METODOLOGIA_VALIDADA, self::QUANTIDADE_AMOSTRA, self::VIABILIDADE_OPERACIONAL, self::TECNICO_HABILITADO, self::MANO_OBRA, self::PLAZO_EXEQUIVEL, self::VIABILIDADE_FINANCIERA, self::VALOR_ADECUADO, self::PLAZO_PAGAMENTO, self::TERCERIZADO, self::ID_FORNECEDOR, self::VALOR_PROPOSTA, self::APROBACION_CLIENTE, self::RESPONSABLE_COMERCIAL, self::APROBADO_RESPONSABLE_COMERCIAL, self::RESPONSABLE_TECNICO, self::APROBADO_RESPONSABLE_TECNICO, self::APROBACION_PROPOSTA, self::CODIGO_PROPOSTA_FINAL, self::VALIDADE_PROPOSTA, self::FORMA_APROBACION, self::PRECIO, self::FORMA_PAGAMENTO,self::NOME ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'analisis_ppal', 'id_proposta_anexo', 'id_proposta', 'id_responsavel', 'id_cliente', 'status', 'data_creacion', 'data_aprobacion', 'descricao', 'plazo', 'viabilidade_tecnica', 'equipamento_apropiado', 'metodologia_validada', 'quantidade_amostra', 'viabilidade_operacional', 'tecnico_habilitado', 'mano_obra', 'plazo_exequivel', 'viabilidade_financiera', 'valor_adecuado', 'plazo_pagamento', 'tercerizado', 'id_fornecedor', 'valor_proposta', 'aprobacion_cliente', 'responsable_comercial', 'aprobado_responsable_comercial', 'responsable_tecnico', 'aprobado_responsable_tecnico', 'aprobacion_proposta', 'codigo_proposta_final', 'validade_proposta', 'forma_aprobacion', 'precio', 'forma_pagamento','nome' ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,36 )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'AnalisisPpal' => 1, 'IdPropostaAnexo' => 2, 'IdProposta' => 3, 'IdResponsavel' => 4, 'IdCliente' => 5, 'Status' => 6, 'DataCreacion' => 7, 'DataAprobacion' => 8, 'Descricao' => 9, 'Plazo' => 10, 'ViabilidadeTecnica' => 11, 'EquipamentoApropiado' => 12, 'MetodologiaValidada' => 13, 'QuantidadeAmostra' => 14, 'ViabilidadeOperacional' => 15, 'TecnicoHabilitado' => 16, 'ManoObra' => 17, 'PlazoExequivel' => 18, 'ViabilidadeFinanciera' => 19, 'ValorAdecuado' => 20, 'PlazoPagamento' => 21, 'Tercerizado' => 22, 'IdFornecedor' => 23, 'ValorProposta' => 24, 'AprobacionCliente' => 25, 'ResponsableComercial' => 26, 'AprobadoResponsableComercial' => 27, 'ResponsableTecnico' => 28, 'AprobadoResponsableTecnico' => 29, 'AprobacionProposta' => 30, 'CodigoPropostaFinal' => 31, 'ValidadeProposta' => 32, 'FormaAprobacion' => 33, 'Precio' => 34, 'FormaPagamento' => 35,'Nome' => 36 ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'analisisPpal' => 1, 'idPropostaAnexo' => 2, 'idProposta' => 3, 'idResponsavel' => 4, 'idCliente' => 5, 'status' => 6, 'dataCreacion' => 7, 'dataAprobacion' => 8, 'descricao' => 9, 'plazo' => 10, 'viabilidadeTecnica' => 11, 'equipamentoApropiado' => 12, 'metodologiaValidada' => 13, 'quantidadeAmostra' => 14, 'viabilidadeOperacional' => 15, 'tecnicoHabilitado' => 16, 'manoObra' => 17, 'plazoExequivel' => 18, 'viabilidadeFinanciera' => 19, 'valorAdecuado' => 20, 'plazoPagamento' => 21, 'tercerizado' => 22, 'idFornecedor' => 23, 'valorProposta' => 24, 'aprobacionCliente' => 25, 'responsableComercial' => 26, 'aprobadoResponsableComercial' => 27, 'responsableTecnico' => 28, 'aprobadoResponsableTecnico' => 29, 'aprobacionProposta' => 30, 'codigoPropostaFinal' => 31, 'validadeProposta' => 32, 'formaAprobacion' => 33, 'precio' => 34, 'formaPagamento' => 35,'nome' => 36 ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::ANALISIS_PPAL => 1, self::ID_PROPOSTA_ANEXO => 2, self::ID_PROPOSTA => 3, self::ID_RESPONSAVEL => 4, self::ID_CLIENTE => 5, self::STATUS => 6, self::DATA_CREACION => 7, self::DATA_APROBACION => 8, self::DESCRICAO => 9, self::PLAZO => 10, self::VIABILIDADE_TECNICA => 11, self::EQUIPAMENTO_APROPIADO => 12, self::METODOLOGIA_VALIDADA => 13, self::QUANTIDADE_AMOSTRA => 14, self::VIABILIDADE_OPERACIONAL => 15, self::TECNICO_HABILITADO => 16, self::MANO_OBRA => 17, self::PLAZO_EXEQUIVEL => 18, self::VIABILIDADE_FINANCIERA => 19, self::VALOR_ADECUADO => 20, self::PLAZO_PAGAMENTO => 21, self::TERCERIZADO => 22, self::ID_FORNECEDOR => 23, self::VALOR_PROPOSTA => 24, self::APROBACION_CLIENTE => 25, self::RESPONSABLE_COMERCIAL => 26, self::APROBADO_RESPONSABLE_COMERCIAL => 27, self::RESPONSABLE_TECNICO => 28, self::APROBADO_RESPONSABLE_TECNICO => 29, self::APROBACION_PROPOSTA => 30, self::CODIGO_PROPOSTA_FINAL => 31, self::VALIDADE_PROPOSTA => 32, self::FORMA_APROBACION => 33, self::PRECIO => 34, self::FORMA_PAGAMENTO => 35,self::NOME => 36 ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'analisis_ppal' => 1, 'id_proposta_anexo' => 2, 'id_proposta' => 3, 'id_responsavel' => 4, 'id_cliente' => 5, 'status' => 6, 'data_creacion' => 7, 'data_aprobacion' => 8, 'descricao' => 9, 'plazo' => 10, 'viabilidade_tecnica' => 11, 'equipamento_apropiado' => 12, 'metodologia_validada' => 13, 'quantidade_amostra' => 14, 'viabilidade_operacional' => 15, 'tecnico_habilitado' => 16, 'mano_obra' => 17, 'plazo_exequivel' => 18, 'viabilidade_financiera' => 19, 'valor_adecuado' => 20, 'plazo_pagamento' => 21, 'tercerizado' => 22, 'id_fornecedor' => 23, 'valor_proposta' => 24, 'aprobacion_cliente' => 25, 'responsable_comercial' => 26, 'aprobado_responsable_comercial' => 27, 'responsable_tecnico' => 28, 'aprobado_responsable_tecnico' => 29, 'aprobacion_proposta' => 30, 'codigo_proposta_final' => 31, 'validade_proposta' => 32, 'forma_aprobacion' => 33, 'precio' => 34, 'forma_pagamento' => 35,'nome' => 36 ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,36 )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. AnalisisPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(AnalisisPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(AnalisisPeer::ID);
		$criteria->addSelectColumn(AnalisisPeer::ANALISIS_PPAL);
		$criteria->addSelectColumn(AnalisisPeer::ID_PROPOSTA_ANEXO);
		$criteria->addSelectColumn(AnalisisPeer::ID_PROPOSTA);
		$criteria->addSelectColumn(AnalisisPeer::ID_RESPONSAVEL);
		$criteria->addSelectColumn(AnalisisPeer::ID_CLIENTE);
		$criteria->addSelectColumn(AnalisisPeer::STATUS);
		$criteria->addSelectColumn(AnalisisPeer::DATA_CREACION);
		$criteria->addSelectColumn(AnalisisPeer::DATA_APROBACION);
		$criteria->addSelectColumn(AnalisisPeer::DESCRICAO);
		$criteria->addSelectColumn(AnalisisPeer::PLAZO);
		$criteria->addSelectColumn(AnalisisPeer::VIABILIDADE_TECNICA);
		$criteria->addSelectColumn(AnalisisPeer::EQUIPAMENTO_APROPIADO);
		$criteria->addSelectColumn(AnalisisPeer::METODOLOGIA_VALIDADA);
		$criteria->addSelectColumn(AnalisisPeer::QUANTIDADE_AMOSTRA);
		$criteria->addSelectColumn(AnalisisPeer::VIABILIDADE_OPERACIONAL);
		$criteria->addSelectColumn(AnalisisPeer::TECNICO_HABILITADO);
		$criteria->addSelectColumn(AnalisisPeer::MANO_OBRA);
		$criteria->addSelectColumn(AnalisisPeer::PLAZO_EXEQUIVEL);
		$criteria->addSelectColumn(AnalisisPeer::VIABILIDADE_FINANCIERA);
		$criteria->addSelectColumn(AnalisisPeer::VALOR_ADECUADO);
		$criteria->addSelectColumn(AnalisisPeer::PLAZO_PAGAMENTO);
		$criteria->addSelectColumn(AnalisisPeer::TERCERIZADO);
		$criteria->addSelectColumn(AnalisisPeer::ID_FORNECEDOR);
		$criteria->addSelectColumn(AnalisisPeer::VALOR_PROPOSTA);
		$criteria->addSelectColumn(AnalisisPeer::APROBACION_CLIENTE);
		$criteria->addSelectColumn(AnalisisPeer::RESPONSABLE_COMERCIAL);
		$criteria->addSelectColumn(AnalisisPeer::APROBADO_RESPONSABLE_COMERCIAL);
		$criteria->addSelectColumn(AnalisisPeer::RESPONSABLE_TECNICO);
		$criteria->addSelectColumn(AnalisisPeer::APROBADO_RESPONSABLE_TECNICO);
		$criteria->addSelectColumn(AnalisisPeer::APROBACION_PROPOSTA);
		$criteria->addSelectColumn(AnalisisPeer::CODIGO_PROPOSTA_FINAL);
		$criteria->addSelectColumn(AnalisisPeer::VALIDADE_PROPOSTA);
		$criteria->addSelectColumn(AnalisisPeer::FORMA_APROBACION);
		$criteria->addSelectColumn(AnalisisPeer::PRECIO);
		$criteria->addSelectColumn(AnalisisPeer::FORMA_PAGAMENTO);
                $criteria->addSelectColumn(AnalisisPeer::NOME);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AnalisisPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AnalisisPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAnalisisPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Analisis
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = AnalisisPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return AnalisisPeer::populateObjects(AnalisisPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			AnalisisPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Analisis $value A Analisis object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Analisis $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Analisis object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Analisis) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Analisis object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Analisis Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to analisis
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = AnalisisPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = AnalisisPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = AnalisisPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				AnalisisPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseAnalisisPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseAnalisisPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new AnalisisTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? AnalisisPeer::CLASS_DEFAULT : AnalisisPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Analisis or Criteria object.
	 *
	 * @param      mixed $values Criteria or Analisis object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnalisisPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAnalisisPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Analisis object
		}

		if ($criteria->containsKey(AnalisisPeer::ID) && $criteria->keyContainsValue(AnalisisPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.AnalisisPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnalisisPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAnalisisPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Analisis or Criteria object.
	 *
	 * @param      mixed $values Criteria or Analisis object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnalisisPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAnalisisPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(AnalisisPeer::ID);
			$selectCriteria->add(AnalisisPeer::ID, $criteria->remove(AnalisisPeer::ID), $comparison);

		} else { // $values is Analisis object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnalisisPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAnalisisPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the analisis table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(AnalisisPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			AnalisisPeer::clearInstancePool();
			AnalisisPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Analisis or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Analisis object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			AnalisisPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Analisis) { // it's a model object
			// invalidate the cache for this single object
			AnalisisPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(AnalisisPeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				AnalisisPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			AnalisisPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Analisis object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Analisis $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Analisis $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(AnalisisPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(AnalisisPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(AnalisisPeer::DATABASE_NAME, AnalisisPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Analisis
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = AnalisisPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(AnalisisPeer::DATABASE_NAME);
		$criteria->add(AnalisisPeer::ID, $pk);

		$v = AnalisisPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AnalisisPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(AnalisisPeer::DATABASE_NAME);
			$criteria->add(AnalisisPeer::ID, $pks, Criteria::IN);
			$objs = AnalisisPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseAnalisisPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseAnalisisPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseAnalisisPeer::buildTableMap();

