<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/01/20 23:13:48
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'projeto_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'projeto_view',
      1 => 'projeto_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'projeto_view',
      1 => 'projeto_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'projeto_view',
      1 => 'projeto_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'projeto_view',
      1 => 'projeto_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'projeto_view',
      1 => 'projeto_delete',
    ),
  ),
);
