<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/09/24 14:41:00
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'pedido_view',
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'pedido_view',
      1 => 'pedido_insert',
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'pedido_view',
      1 => 'pedido_insert',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'pedido_view',
      1 => 'pedido_update',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'pedido_view',
      1 => 'pedido_delete',
    ),
  ),
  'deleteall' => 
  array (
    'credentials' => 
    array (
      0 => 'pedido_view',
      1 => 'pedido_delete',
    ),
  ),
);
