<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/31 17:59:21
sfConfig::add(array(
  'mod_horasbillability_enabled' => true,
  'mod_horasbillability_view_class' => 'sfPHP',
));
