<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/01/22 21:26:26
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'lx_account_view',
    ),
  ),
);
