<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/01/23 20:55:20
sfConfig::add(array(
  'mod_horasbillability_enabled' => true,
  'mod_horasbillability_view_class' => 'sfPHP',
));
