<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/01/23 14:11:41
sfConfig::add(array(
  'mod_preco_funcionario_enabled' => true,
  'mod_preco_funcionario_view_class' => 'sfPHP',
));
