all:
  http_metas:
    content-type: text/html

  metas:
    title:        Error page
    language:     en

  stylesheets:    [-*, main]

  javascripts:    [-*]

  has_layout:     on
  layout:         layoutError
