<?php


/**
 * This class defines the structure of the 'projeto' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 03/04/2014 12:04:42
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.sgws.map
 */
class ProjetoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.sgws.map.ProjetoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('projeto');
		$this->setPhpName('Projeto');
		$this->setClassname('Projeto');
		$this->setPackage('lib.model.sgws');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('CODIGO_PROJETO', 'CodigoProjeto', 'INTEGER', true, 11, null);
		$this->addColumn('CODIGO_SGWS', 'CodigoSgws', 'VARCHAR', false, 50, null);
		$this->addColumn('CODIGO_PROPOSTA', 'CodigoProposta', 'INTEGER', false, 11, null);
		$this->addColumn('NOME_PROJETO', 'NomeProjeto', 'VARCHAR', false, 255, null);
		$this->addColumn('CODIGO_TIPO', 'CodigoTipo', 'INTEGER', false, 11, null);
		$this->addColumn('GERENTE', 'Gerente', 'INTEGER', false, 11, null);
		$this->addColumn('CODIGO_CADASTRO', 'CodigoCadastro', 'INTEGER', false, 11, null);
		$this->addColumn('DATA_IR_PROJETO', 'DataIrProjeto', 'TIMESTAMP', false, null, null);
		$this->addColumn('DATA_FR_PROJETO', 'DataFrProjeto', 'TIMESTAMP', false, null, null);
		$this->addColumn('DATA_IP_PROJETO', 'DataIpProjeto', 'TIMESTAMP', false, null, null);
		$this->addColumn('DATA_FP_PROJETO', 'DataFpProjeto', 'TIMESTAMP', false, null, null);
		$this->addColumn('STATUS', 'Status', 'INTEGER', false, 11, null);
		$this->addColumn('DESCRICAO_PROJETO', 'DescricaoProjeto', 'LONGVARCHAR', false, null, null);
		$this->addColumn('NP', 'Np', 'VARCHAR', false, 50, null);
		$this->addColumn('SAIDA_PREVISTA_PROJETO', 'SaidaPrevistaProjeto', 'INTEGER', false, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ProjetoTableMap
