<?php


/**
 * This class defines the structure of the 'proposta' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 03/04/2014 12:04:44
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.sgws.map
 */
class PropostaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.sgws.map.PropostaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('proposta');
		$this->setPhpName('Proposta');
		$this->setClassname('Proposta');
		$this->setPackage('lib.model.sgws');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('CODIGO_PROPOSTA', 'CodigoProposta', 'INTEGER', true, 11, null);
		$this->addColumn('CODIGO_SGWS', 'CodigoSgws', 'VARCHAR', false, 10, null);
		$this->addColumn('CODIGO_PROJETO', 'CodigoProjeto', 'INTEGER', true, 11, null);
		$this->addColumn('CODIGO_SGWS_PROJETO', 'CodigoSgwsProjeto', 'VARCHAR', true, 10, null);
		$this->addColumn('CODIGO_CENTRO', 'CodigoCentro', 'INTEGER', true, 11, null);
		$this->addColumn('ID_NEGOCIACAO', 'IdNegociacao', 'INTEGER', true, 11, null);
		$this->addColumn('CODIGO_TIPO', 'CodigoTipo', 'INTEGER', true, 11, null);
		$this->addColumn('DATA_INICIO', 'DataInicio', 'DATE', false, null, null);
		$this->addColumn('DATA_FINAL', 'DataFinal', 'TIMESTAMP', false, null, null);
		$this->addColumn('DATA_IR_PROJETO', 'DataIrProjeto', 'DATE', true, null, null);
		$this->addColumn('DATA_FR_PROJETO', 'DataFrProjeto', 'DATE', true, null, null);
		$this->addColumn('NOME_PROPOSTA', 'NomeProposta', 'VARCHAR', false, 255, null);
		$this->addColumn('CLIENTE', 'Cliente', 'INTEGER', false, 11, null);
		$this->addColumn('SATISFACAO_CLIENTE', 'SatisfacaoCliente', 'INTEGER', false, 2, null);
		$this->addColumn('NAO_CONFORMIDADE', 'NaoConformidade', 'INTEGER', false, 6, null);
		$this->addColumn('GERENTE', 'Gerente', 'INTEGER', false, 11, null);
		$this->addColumn('STATUS', 'Status', 'INTEGER', false, 11, null);
		$this->addColumn('ID_STATUS_PROPOSTA', 'IdStatusProposta', 'INTEGER', true, 11, null);
		$this->addColumn('STATUS_ANALISIS', 'StatusAnalisis', 'CHAR', true, null, null);
		$this->addColumn('VISUALIZACION', 'Visualizacion', 'CHAR', true, null, '0');
		$this->addColumn('APR', 'Apr', 'CHAR', true, null, '');
		$this->addColumn('PROPOSTA', 'Proposta', 'LONGVARCHAR', false, null, null);
		$this->addColumn('VALOR', 'Valor', 'DECIMAL', false, 10, null);
		$this->addColumn('VALOR_PREV_HH', 'ValorPrevHh', 'DECIMAL', false, 10, null);
		$this->addColumn('ID_PRIORIDADE', 'IdPrioridade', 'INTEGER', true, 11, null);
		$this->addColumn('HORAS_VENDIDAS', 'HorasVendidas', 'DECIMAL', true, 10, null);
		$this->addColumn('HORAS_TRABAJADAS', 'HorasTrabajadas', 'DECIMAL', true, 10, null);
		$this->addColumn('COEFICIENTE', 'Coeficiente', 'DECIMAL', true, 10, null);
		$this->addColumn('FLAG_PROJETO', 'FlagProjeto', 'TINYINT', false, 4, null);
		$this->addColumn('TIPO', 'Tipo', 'INTEGER', false, 11, null);
		$this->addColumn('CODIGO_VELHIO', 'CodigoVelhio', 'INTEGER', true, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PropostaTableMap
