<?php


/**
 * This class defines the structure of the 'tarefa' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 03/04/2014 12:04:44
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.sgws.map
 */
class TarefaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.sgws.map.TarefaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tarefa');
		$this->setPhpName('Tarefa');
		$this->setClassname('Tarefa');
		$this->setPackage('lib.model.sgws');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('CODIGOTAREFA', 'Codigotarefa', 'INTEGER', true, 11, null);
		$this->addColumn('TAREFA_PARENT', 'TarefaParent', 'INTEGER', true, 11, 0);
		$this->addColumn('RESPONSAVEL', 'Responsavel', 'INTEGER', false, 11, null);
		$this->addColumn('CODIGOPROJETO', 'Codigoprojeto', 'INTEGER', false, 11, null);
		$this->addColumn('VISUALIZACAO', 'Visualizacao', 'CHAR', false, null, null);
		$this->addColumn('DESCRICAO', 'Descricao', 'INTEGER', false, 11, null);
		$this->addColumn('TIPO_TAREFA', 'TipoTarefa', 'INTEGER', false, 11, null);
		$this->addColumn('DATAIRTAREFA', 'Datairtarefa', 'DATE', false, null, null);
		$this->addColumn('DATAFRTAREFA', 'Datafrtarefa', 'DATE', false, null, null);
		$this->addColumn('STATUS', 'Status', 'INTEGER', false, 11, null);
		$this->addColumn('DESPESAPREVISTA', 'Despesaprevista', 'DECIMAL', false, 10, null);
		$this->addColumn('HORASPREVISTAS', 'Horasprevistas', 'DECIMAL', false, 10, null);
		$this->addColumn('OBSERVACOES', 'Observacoes', 'LONGVARCHAR', false, null, null);
		$this->addColumn('INFORMACOES', 'Informacoes', 'LONGVARCHAR', false, null, null);
		$this->addColumn('ID_PRIORIDADE', 'IdPrioridade', 'INTEGER', false, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TarefaTableMap
