all:
  is_secure: on


index:
  credentials: [lx_user_permission_view]

new:
  credentials: [lx_user_permission_view, lx_user_permission_insert]

create:
  credentials: [lx_user_permission_view, lx_user_permission_insert]

edit:
  credentials: [lx_user_permission_view, lx_user_permission_update]

delete:
  credentials: [lx_user_permission_view, lx_user_permission_delete]

deleteAll:
  credentials: [lx_user_permission_view, lx_user_permission_delete]

changeStatus:
  credentials: [lx_user_permission_view, lx_user_permission_update]

changePrivileges:
  credentials: [lx_user_permission_view, lx_user_permission_update]