<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/09/29 16:56:33
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'relatorio_view',
    ),
  ),
);
