<?php

/**
 * Base static class for performing query and update operations on the 'cadastro_fisica' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 03/04/2014 12:04:39
 *
 * @package    plugins.sfUserV2Plugin.lib.model.om
 */
abstract class BaseCadastroFisicaPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'cadastro_fisica';

	/** the related Propel class for this table */
	const OM_CLASS = 'CadastroFisica';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.sfUserV2Plugin.lib.model.CadastroFisica';

	/** the related TableMap class for this table */
	const TM_CLASS = 'CadastroFisicaTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 28;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID_CADASTRO_FISICA field */
	const ID_CADASTRO_FISICA = 'cadastro_fisica.ID_CADASTRO_FISICA';

	/** the column name for the ID_USER field */
	const ID_USER = 'cadastro_fisica.ID_USER';

	/** the column name for the NOME field */
	const NOME = 'cadastro_fisica.NOME';

	/** the column name for the CPF field */
	const CPF = 'cadastro_fisica.CPF';

	/** the column name for the RG field */
	const RG = 'cadastro_fisica.RG';

	/** the column name for the SEXO field */
	const SEXO = 'cadastro_fisica.SEXO';

	/** the column name for the CARGO field */
	const CARGO = 'cadastro_fisica.CARGO';

	/** the column name for the DATA_NACIMENTO field */
	const DATA_NACIMENTO = 'cadastro_fisica.DATA_NACIMENTO';

	/** the column name for the DDI_TELEFONE field */
	const DDI_TELEFONE = 'cadastro_fisica.DDI_TELEFONE';

	/** the column name for the DDD_TELEFONE field */
	const DDD_TELEFONE = 'cadastro_fisica.DDD_TELEFONE';

	/** the column name for the TELEFONE field */
	const TELEFONE = 'cadastro_fisica.TELEFONE';

	/** the column name for the DDI_CELULAR field */
	const DDI_CELULAR = 'cadastro_fisica.DDI_CELULAR';

	/** the column name for the DDD_CELULAR field */
	const DDD_CELULAR = 'cadastro_fisica.DDD_CELULAR';

	/** the column name for the CELULAR field */
	const CELULAR = 'cadastro_fisica.CELULAR';

	/** the column name for the ENDERECO field */
	const ENDERECO = 'cadastro_fisica.ENDERECO';

	/** the column name for the NUMERO field */
	const NUMERO = 'cadastro_fisica.NUMERO';

	/** the column name for the COMPLEMENTO field */
	const COMPLEMENTO = 'cadastro_fisica.COMPLEMENTO';

	/** the column name for the PAIS field */
	const PAIS = 'cadastro_fisica.PAIS';

	/** the column name for the ID_UF field */
	const ID_UF = 'cadastro_fisica.ID_UF';

	/** the column name for the ID_MUNICIPIO field */
	const ID_MUNICIPIO = 'cadastro_fisica.ID_MUNICIPIO';

	/** the column name for the BARRIO field */
	const BARRIO = 'cadastro_fisica.BARRIO';

	/** the column name for the CEP field */
	const CEP = 'cadastro_fisica.CEP';

	/** the column name for the FORMA_CONTRATACAO field */
	const FORMA_CONTRATACAO = 'cadastro_fisica.FORMA_CONTRATACAO';

	/** the column name for the DATA_REGISTRO field */
	const DATA_REGISTRO = 'cadastro_fisica.DATA_REGISTRO';

	/** the column name for the DATA_ADMISSAO field */
	const DATA_ADMISSAO = 'cadastro_fisica.DATA_ADMISSAO';

	/** the column name for the DATA_EMISSAO field */
	const DATA_EMISSAO = 'cadastro_fisica.DATA_EMISSAO';

	/** the column name for the OBSERVACOES field */
	const OBSERVACOES = 'cadastro_fisica.OBSERVACOES';

	/** the column name for the DEPENDENTES field */
	const DEPENDENTES = 'cadastro_fisica.DEPENDENTES';

	/**
	 * An identiy map to hold any loaded instances of CadastroFisica objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array CadastroFisica[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('IdCadastroFisica', 'IdUser', 'Nome', 'Cpf', 'Rg', 'Sexo', 'Cargo', 'DataNacimento', 'DdiTelefone', 'DddTelefone', 'Telefone', 'DdiCelular', 'DddCelular', 'Celular', 'Endereco', 'Numero', 'Complemento', 'Pais', 'IdUf', 'IdMunicipio', 'Barrio', 'Cep', 'FormaContratacao', 'DataRegistro', 'DataAdmissao', 'DataEmissao', 'Observacoes', 'Dependentes', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('idCadastroFisica', 'idUser', 'nome', 'cpf', 'rg', 'sexo', 'cargo', 'dataNacimento', 'ddiTelefone', 'dddTelefone', 'telefone', 'ddiCelular', 'dddCelular', 'celular', 'endereco', 'numero', 'complemento', 'pais', 'idUf', 'idMunicipio', 'barrio', 'cep', 'formaContratacao', 'dataRegistro', 'dataAdmissao', 'dataEmissao', 'observacoes', 'dependentes', ),
		BasePeer::TYPE_COLNAME => array (self::ID_CADASTRO_FISICA, self::ID_USER, self::NOME, self::CPF, self::RG, self::SEXO, self::CARGO, self::DATA_NACIMENTO, self::DDI_TELEFONE, self::DDD_TELEFONE, self::TELEFONE, self::DDI_CELULAR, self::DDD_CELULAR, self::CELULAR, self::ENDERECO, self::NUMERO, self::COMPLEMENTO, self::PAIS, self::ID_UF, self::ID_MUNICIPIO, self::BARRIO, self::CEP, self::FORMA_CONTRATACAO, self::DATA_REGISTRO, self::DATA_ADMISSAO, self::DATA_EMISSAO, self::OBSERVACOES, self::DEPENDENTES, ),
		BasePeer::TYPE_FIELDNAME => array ('id_cadastro_fisica', 'id_user', 'nome', 'cpf', 'rg', 'sexo', 'cargo', 'data_nacimento', 'ddi_telefone', 'ddd_telefone', 'telefone', 'ddi_celular', 'ddd_celular', 'celular', 'endereco', 'numero', 'complemento', 'pais', 'id_uf', 'id_municipio', 'barrio', 'cep', 'forma_contratacao', 'data_registro', 'data_admissao', 'data_emissao', 'observacoes', 'dependentes', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('IdCadastroFisica' => 0, 'IdUser' => 1, 'Nome' => 2, 'Cpf' => 3, 'Rg' => 4, 'Sexo' => 5, 'Cargo' => 6, 'DataNacimento' => 7, 'DdiTelefone' => 8, 'DddTelefone' => 9, 'Telefone' => 10, 'DdiCelular' => 11, 'DddCelular' => 12, 'Celular' => 13, 'Endereco' => 14, 'Numero' => 15, 'Complemento' => 16, 'Pais' => 17, 'IdUf' => 18, 'IdMunicipio' => 19, 'Barrio' => 20, 'Cep' => 21, 'FormaContratacao' => 22, 'DataRegistro' => 23, 'DataAdmissao' => 24, 'DataEmissao' => 25, 'Observacoes' => 26, 'Dependentes' => 27, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('idCadastroFisica' => 0, 'idUser' => 1, 'nome' => 2, 'cpf' => 3, 'rg' => 4, 'sexo' => 5, 'cargo' => 6, 'dataNacimento' => 7, 'ddiTelefone' => 8, 'dddTelefone' => 9, 'telefone' => 10, 'ddiCelular' => 11, 'dddCelular' => 12, 'celular' => 13, 'endereco' => 14, 'numero' => 15, 'complemento' => 16, 'pais' => 17, 'idUf' => 18, 'idMunicipio' => 19, 'barrio' => 20, 'cep' => 21, 'formaContratacao' => 22, 'dataRegistro' => 23, 'dataAdmissao' => 24, 'dataEmissao' => 25, 'observacoes' => 26, 'dependentes' => 27, ),
		BasePeer::TYPE_COLNAME => array (self::ID_CADASTRO_FISICA => 0, self::ID_USER => 1, self::NOME => 2, self::CPF => 3, self::RG => 4, self::SEXO => 5, self::CARGO => 6, self::DATA_NACIMENTO => 7, self::DDI_TELEFONE => 8, self::DDD_TELEFONE => 9, self::TELEFONE => 10, self::DDI_CELULAR => 11, self::DDD_CELULAR => 12, self::CELULAR => 13, self::ENDERECO => 14, self::NUMERO => 15, self::COMPLEMENTO => 16, self::PAIS => 17, self::ID_UF => 18, self::ID_MUNICIPIO => 19, self::BARRIO => 20, self::CEP => 21, self::FORMA_CONTRATACAO => 22, self::DATA_REGISTRO => 23, self::DATA_ADMISSAO => 24, self::DATA_EMISSAO => 25, self::OBSERVACOES => 26, self::DEPENDENTES => 27, ),
		BasePeer::TYPE_FIELDNAME => array ('id_cadastro_fisica' => 0, 'id_user' => 1, 'nome' => 2, 'cpf' => 3, 'rg' => 4, 'sexo' => 5, 'cargo' => 6, 'data_nacimento' => 7, 'ddi_telefone' => 8, 'ddd_telefone' => 9, 'telefone' => 10, 'ddi_celular' => 11, 'ddd_celular' => 12, 'celular' => 13, 'endereco' => 14, 'numero' => 15, 'complemento' => 16, 'pais' => 17, 'id_uf' => 18, 'id_municipio' => 19, 'barrio' => 20, 'cep' => 21, 'forma_contratacao' => 22, 'data_registro' => 23, 'data_admissao' => 24, 'data_emissao' => 25, 'observacoes' => 26, 'dependentes' => 27, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. CadastroFisicaPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(CadastroFisicaPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(CadastroFisicaPeer::ID_CADASTRO_FISICA);
		$criteria->addSelectColumn(CadastroFisicaPeer::ID_USER);
		$criteria->addSelectColumn(CadastroFisicaPeer::NOME);
		$criteria->addSelectColumn(CadastroFisicaPeer::CPF);
		$criteria->addSelectColumn(CadastroFisicaPeer::RG);
		$criteria->addSelectColumn(CadastroFisicaPeer::SEXO);
		$criteria->addSelectColumn(CadastroFisicaPeer::CARGO);
		$criteria->addSelectColumn(CadastroFisicaPeer::DATA_NACIMENTO);
		$criteria->addSelectColumn(CadastroFisicaPeer::DDI_TELEFONE);
		$criteria->addSelectColumn(CadastroFisicaPeer::DDD_TELEFONE);
		$criteria->addSelectColumn(CadastroFisicaPeer::TELEFONE);
		$criteria->addSelectColumn(CadastroFisicaPeer::DDI_CELULAR);
		$criteria->addSelectColumn(CadastroFisicaPeer::DDD_CELULAR);
		$criteria->addSelectColumn(CadastroFisicaPeer::CELULAR);
		$criteria->addSelectColumn(CadastroFisicaPeer::ENDERECO);
		$criteria->addSelectColumn(CadastroFisicaPeer::NUMERO);
		$criteria->addSelectColumn(CadastroFisicaPeer::COMPLEMENTO);
		$criteria->addSelectColumn(CadastroFisicaPeer::PAIS);
		$criteria->addSelectColumn(CadastroFisicaPeer::ID_UF);
		$criteria->addSelectColumn(CadastroFisicaPeer::ID_MUNICIPIO);
		$criteria->addSelectColumn(CadastroFisicaPeer::BARRIO);
		$criteria->addSelectColumn(CadastroFisicaPeer::CEP);
		$criteria->addSelectColumn(CadastroFisicaPeer::FORMA_CONTRATACAO);
		$criteria->addSelectColumn(CadastroFisicaPeer::DATA_REGISTRO);
		$criteria->addSelectColumn(CadastroFisicaPeer::DATA_ADMISSAO);
		$criteria->addSelectColumn(CadastroFisicaPeer::DATA_EMISSAO);
		$criteria->addSelectColumn(CadastroFisicaPeer::OBSERVACOES);
		$criteria->addSelectColumn(CadastroFisicaPeer::DEPENDENTES);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CadastroFisicaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CadastroFisicaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseCadastroFisicaPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     CadastroFisica
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = CadastroFisicaPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return CadastroFisicaPeer::populateObjects(CadastroFisicaPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			CadastroFisicaPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      CadastroFisica $value A CadastroFisica object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(CadastroFisica $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getIdCadastroFisica();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A CadastroFisica object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof CadastroFisica) {
				$key = (string) $value->getIdCadastroFisica();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or CadastroFisica object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     CadastroFisica Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to cadastro_fisica
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = CadastroFisicaPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = CadastroFisicaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = CadastroFisicaPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				CadastroFisicaPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseCadastroFisicaPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseCadastroFisicaPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new CadastroFisicaTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? CadastroFisicaPeer::CLASS_DEFAULT : CadastroFisicaPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a CadastroFisica or Criteria object.
	 *
	 * @param      mixed $values Criteria or CadastroFisica object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroFisicaPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseCadastroFisicaPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from CadastroFisica object
		}

		if ($criteria->containsKey(CadastroFisicaPeer::ID_CADASTRO_FISICA) && $criteria->keyContainsValue(CadastroFisicaPeer::ID_CADASTRO_FISICA) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.CadastroFisicaPeer::ID_CADASTRO_FISICA.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroFisicaPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseCadastroFisicaPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a CadastroFisica or Criteria object.
	 *
	 * @param      mixed $values Criteria or CadastroFisica object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroFisicaPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseCadastroFisicaPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(CadastroFisicaPeer::ID_CADASTRO_FISICA);
			$selectCriteria->add(CadastroFisicaPeer::ID_CADASTRO_FISICA, $criteria->remove(CadastroFisicaPeer::ID_CADASTRO_FISICA), $comparison);

		} else { // $values is CadastroFisica object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseCadastroFisicaPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseCadastroFisicaPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the cadastro_fisica table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(CadastroFisicaPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			CadastroFisicaPeer::clearInstancePool();
			CadastroFisicaPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a CadastroFisica or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or CadastroFisica object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			CadastroFisicaPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof CadastroFisica) { // it's a model object
			// invalidate the cache for this single object
			CadastroFisicaPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(CadastroFisicaPeer::ID_CADASTRO_FISICA, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				CadastroFisicaPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			CadastroFisicaPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given CadastroFisica object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      CadastroFisica $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(CadastroFisica $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(CadastroFisicaPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(CadastroFisicaPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(CadastroFisicaPeer::DATABASE_NAME, CadastroFisicaPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     CadastroFisica
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = CadastroFisicaPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(CadastroFisicaPeer::DATABASE_NAME);
		$criteria->add(CadastroFisicaPeer::ID_CADASTRO_FISICA, $pk);

		$v = CadastroFisicaPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroFisicaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(CadastroFisicaPeer::DATABASE_NAME);
			$criteria->add(CadastroFisicaPeer::ID_CADASTRO_FISICA, $pks, Criteria::IN);
			$objs = CadastroFisicaPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseCadastroFisicaPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseCadastroFisicaPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseCadastroFisicaPeer::buildTableMap();

