<?php


/**
 * Skeleton subclass for performing query and update operations on the 'horas_billability' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 07/01/2014 10:11:32
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.sgws
 */
class HorasBillabilityPeer extends BaseHorasBillabilityPeer {
    
    public static function getCheckAno($id,$ano)
    {
        $c = new Criteria();
        if($id)
        {
            $c->add(self::CODIGO, $id, Criteria::NOT_EQUAL);
        }
        
        $c->add(self::ANO, $ano, Criteria::EQUAL);
        return self::doCount($c);
        //Cambiar por return !empty($profiles) ? $profiles : false;
    }
    
    public static function getAnoHorasMes($ano)
    {
        $c = new Criteria();
        $c->add(self::ANO, $ano, Criteria::EQUAL);
        
        
        return self::doSelectOne($c);
        //Cambiar por return !empty($profiles) ? $profiles : false;
    }

} // HorasBillabilityPeer
