<?php


/**
 * Skeleton subclass for performing query and update operations on the 'uf' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 08/03/2013 18:29:25
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.sgws
 */
class UfPeer extends BaseUfPeer {
    
      public static function getTodosUf()
  {
    $c = new Criteria();
    $c->addAscendingOrderByColumn('name_uf');

    return self::doSelect($c);
  }
  
  public static function getIdUf($nome)
  {
      $c = new Criteria();
      $c->add(self::NAME_UF, "%".$nome."%", Criteria::LIKE);
      return self::doSelectOne($c);
  }

} // UfPeer
