<?php


/**
 * Skeleton subclass for representing a row from the 'sf_album_content' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon May 10 14:23:32 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfLynxPhotoAlbumPlugin.lib.model
 */
class SfAlbumContent extends BaseSfAlbumContent {

} // SfAlbumContent
